{{- if .Values.initDB.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "xxl-job-admin.fullname" . }}-init-db
  annotations:
    "helm.sh/hook-weight": "1"
    # "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels: {{- include "xxl-job-admin.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels: {{- include "xxl-job-admin.labels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "xxl-job-admin.fullname" . }}-config
      containers:
      - name: init-db
        image: "{{ .Values.initDB.image.registry }}:{{ .Values.initDB.image.tag }}"
        imagePullPolicy: {{ .Values.initDB.image.pullPolicy }}
        command: ['bash', '-ce']
        args:
          - |
            sed "/e10adc3949ba59abbe56e057f20f883e/s/admin/$(XXL_ADMIN_USER)/g;s/e10adc3949ba59abbe56e057f20f883e/$(XXL_ADMIN_PASSWORD)/g" /config/init.sql > /tmp/init.sql
            trap 'rm -f /tmp/init.sql' EXIT
            mysql -u$(MYSQL_USER) -p$(MYSQL_PASSWORD) -h$(MYSQL_HOST) -P$(MYSQL_PORT) $(MYSQL_DATABASE) < /tmp/init.sql
        envFrom: 
          - secretRef:
              name: {{ include "xxl-job-admin.fullname" . }}
        volumeMounts:
            - name: config
              mountPath: /config
      restartPolicy: OnFailure
  parallelism: 1
  completions: 1
  backoffLimit: 6
{{- end }}
