apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xxl-job-admin.fullname" . }}
  labels:
    {{- include "xxl-job-admin.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_HOST: {{ required "mysql.host is required" .Values.mysql.host | b64enc | quote }}
  MYSQL_PORT: "{{ .Values.mysql.port }}"
  MYSQL_DATABASE: {{ required "mysql.database is required" .Values.mysql.database | b64enc | quote }}
  {{- with .Values.mysql.user }}
  MYSQL_USER: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.mysql.password }}
  MYSQL_PASSWORD: {{ . | b64enc | quote }}
  {{- end }}