{{- range .Values.upstreamServers }}
{{ $cert := get $.Values.certs .name }}
{{- if $cert }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nginx.fullname" $ }}-{{ .name }}
  labels:
    {{- include "nginx.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := $cert }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
