name: Release Charts

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v2.1
        with:
          version: v3.12.2

      - name: Install unittest plugin
        run: |
          helm env
          helm plugin install https://github.com/quintush/helm-unittest --version 0.2.8

      - name: Run unittest
        run: |
          for chart in charts/*; do
            helm unittest $chart
          done

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        if: github.ref_name == 'main'
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
